import sys
import os

# Ensure the project root is in the path to import src modules
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from src.retriever import get_retriever, create_rag_chain

def query_codebase(question: str) -> str:
    """
    Queries the codebase using semantic search and RAG to answer a question.
    
    Args:
        question: The question to ask about the codebase.
        
    Returns:
        The answer generated by the RAG pipeline.
    """
    try:
        retriever = get_retriever()
        rag_chain = create_rag_chain(retriever)
        
        # Invoke the chain
        response = rag_chain.invoke(question)
        return response
    except Exception as e:
        return f"Error querying codebase: {str(e)}"
